### ISSUE TITLE
Docker restarting over and over

### ISSUE THREAD

**Issue by aaryswastaken** [sleede/fab-manager#193]
Hello,

I just finished my install of fabmanager into a VM (running on proxmox) but by trying to connect to the web interface, I have a nice `ERR_CONNECTION_REFUSED`. 
I tried both http and https, on port 3000, 80, 443, 8080 ...
Did I just missed someting in the installation process ?

So I ran `sudo docker ps` in order to see if the dockers are running and I saw that the postgres docker is restarting over and over : The status is always `Restarting (1) N seconds ago` (N is just a value) 

I'm running Ubuntu 19.04 on a VM. The log isn't showing anything special.

I tried running 
`sudo lsof -i -P -n | grep LISTEN` : 
Port 80 and 443 are open and listening (created by `docker-pr`)

There is **no** firewall set on the Hypervisor

Does anyone tried to run FabManager on Proxmox ?

(EDIT) I allocated it all the CPU power I could, this added nginx to the list of dockers, and it's restarting over and over, with postgres

**Comment by sylvainbx** [comment]
Hello @CofeDrink68 
Can you post here the messages from `docker-compose logs postgres` and the version you're using?

**Comment by sylvainbx** [comment]
Hi @CofeDrink68 ,
Can you try to modify your `docker-compose.yml` file according to this:

```yml
  postgres:
    image: postgres:9.6
    volumes:
      - ${PWD}/postgresql:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
```

Please tell us if this fixes your issue
