### ISSUE TITLE
Assets precompile failed : error Couldn't find the binary git

### ISSUE THREAD

**Issue by guidtz** [sleede/fab-manager#236]
Hello, i'll try to upgrade from 4.2.3 to 4.6.3.

So When I'll try to recompile assets I have those error : 
```
yarn install v1.19.2
[1/4] Resolving packages...
[2/4] Fetching packages...
error Couldn't find the binary git
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
And assets are not recreated. 

Thanks for you're help

**Comment by sylvainbx** [comment]
Hi @guidtz ,
You can safely ignore the message `error Couldn't find the binary git`.

However, the assets are now created in `/apps/fabmanager/public/packs/` (previously it was in `/apps/fabmanager/public/assets`). Can you check the content of that folder ? 
Specifically, can you report here the content of `/apps/fabmanager/public/packs/manifest.json` ?

**Comment by guidtz** [comment]
@sylvainbx ok but the home page of fabmanager is empty after migration and when I try to connect I have these error : Unprocessable Entity (perhaps another error).

[manifest.json.txt](https://github.com/sleede/fab-manager/files/5532252/manifest.json.txt)

Thanks for you're help

**Comment by guidtz** [comment]
@sylvainbx any idea why front page is white and why I could not connect to Fab Manager ?

Thanks

**Comment by sylvainbx** [comment]
Your `manifest.json` file seems ok. Can you check your volumes bindings in the `docker-compose.yml` file?

**Comment by guidtz** [comment]
Do you see something strange ? 

```
version: '2'
services:
  fabmanager:
    image: sleede/fab-manager
    environment:
      RAILS_ENV: production
      RACK_ENV: production
    env_file:
      - ${PWD}/config/env
    volumes:
      - ${PWD}/public/packs:/usr/src/app/public/packs
      - ${PWD}/public/uploads:/usr/src/app/public/uploads
      - ${PWD}/invoices:/usr/src/app/invoices
      - ${PWD}/exports:/usr/src/app/exports
      - ${PWD}/log:/var/log/supervisor
      - ${PWD}/plugins:/usr/src/app/plugins
      - ${PWD}/accounting:/usr/src/app/accounting
      - ${PWD}/imports:/usr/src/app/imports
    depends_on:
      - postgres
      - redis
      - elasticsearch
    restart: always
    networks:
      - fabmanager
  postgres:
    image: postgres:9.6
    volumes:
      - /home/debian/fabm-bocal/postgresql-9.6:/var/lib/postgresql/data
    restart: always
    networks:
      - fabmanager
  elasticsearch:
    image: elasticsearch:5.6
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ${PWD}/elasticsearch:/usr/share/elasticsearch/data
    restart: always
    networks:
      - fabmanager
  redis:
    image: redis:6-alpine
    volumes:
      - ${PWD}/redis:/data
    restart: always
    networks:
      - fabmanager
  nginx:
    image: nginx:1.9
    #    ports:
    #  - "80:80"
    #  - "443:443"
    volumes:
      - ${PWD}/config/nginx:/etc/nginx/conf.d
      - ${PWD}/letsencrypt/etc:/etc/letsencrypt
      - ${PWD}/log:/var/log/nginx
    volumes_from:
      - fabmanager:ro
    links:
      - fabmanager:fabmanager
    restart: always
    networks:
      - traefik-proxy
      - fabmanager
    labels:
      traefik.enable: "true"
      traefik.port: "80"
      traefik.docker.network: "traefik-proxy"
      traefik.frontend.entryPoints: "http,https"
      traefik.networks: "traefik-proxy"
      traefik.frontend.rule: "Host:mon.url.com"
networks:
  fabmanager:
  traefik-proxy:
    external: true
```

NB I use Traefik as proxy
